### ISSUE TITLE
Version issues in reading LaMEM timesteps

### ISSUE THREAD

**Issue by jaime-almeida** [JuliaGeodynamics/LaMEM.jl#18]
Hello,

I was trying to import a simulation back into Julia to perform some post-processing but I'm struggling to do so.

Specifically, running the Read_LaMEM_timestep function returns an AssertionError:
```
julia> using LaMEM
julia> test = Read_LaMEM_timestep(model_file, 50, model_directory)
AssertionError: version >= v"1.0"
```

I've checked the XML version on the output files (both the \*.pvd and \*.pvtr/\*.pvts) files and I found this:
```
<?xml version="1.0"?>
<VTKFile type="Collection" version="0.1" byte_order="LittleEndian">
```
I'm guessing the VTKFile type version is triggering this error but I am quite clueless as how to solve it.

Cheers

**Comment by boriskaus** [comment]
`ReadVTK` recently changed something in this respect, and I believe we now support the latest version of that package. Which one are you using?

**Comment by jaime-almeida** [comment]
This issue appeared when I tried to load a simulation I ran on my HPC installation, which has not been updated in a while. That should be what is tripping me! 
I'm going to update my LaMEM installation and try this again.

Nevertheless, my current `ReadVTK`  version is `v0.1.9`.

**Comment by boriskaus** [comment]
you can try updating ReadVTK to 0.2.0

**Comment by jaime-almeida** [comment]
Updated the HPC installation, issue solved. Thank you so much Boris!
