### ISSUE TITLE
Passive tracers

### ISSUE THREAD

**Issue by NicolasRiel** [JuliaGeodynamics/LaMEM.jl#27]
It would be great if the option to add passive tracers to LaMEM model would be available using the Julia wrapper!

**Comment by boriskaus** [comment]
yes that is currently not yet created; shouldn't be hard to do.

**Comment by wenrongcao** [comment]
It will be great if we can directly set up passive tracers in julia.

**Comment by boriskaus** [comment]
Ok, bumped it higher on my list…

**Comment by boriskaus** [comment]
closed with PR #31
