### ISSUE TITLE
Error with MUMPS

### ISSUE THREAD

**Issue by mthielma** [JuliaGeodynamics/LaMEM.jl#57]
I tried to run the falling block example from the README (Section 3), but with the direct solver input file FallingBlock_DirectSolver.dat When I run it with:

`run_lamem(ParamFile,` 4,"-time_end 1")`

I get (I just quote the relevant stuff):

```
================================= STEP 1 =================================
--------------------------------------------------------------------------
Current time        : 0.00000000 [ ] 
Tentative time step : 10.00000000 [ ] 
--------------------------------------------------------------------------
  0 SNES Function norm 7.310266752999e+01 
  0 PICARD ||F||/||F0||=1.000000e+00 
  ** Instance Error 1 in DMUMPS_F77           0
application called MPI_Abort(MPI_COMM_WORLD, -99) - process 1


```

**Comment by boriskaus** [comment]
Which machine and julia version?

**Comment by mthielma** [comment]
Mac, Ventura 13.3, julia 1.10.3

**Comment by mthielma** [comment]
Update: 
running the tests also results in a fail of the parallel test.
I tried with different direct solvers and they all fail. So I'm thinking it may not be LaMEM, but an issue with PETSc and the installed direct solvers?

**Comment by boriskaus** [comment]
`PETSc_jll` 3.19.6 is compiled with support for MUMPS and SuperLU_Dist on Mac and linux. So the next compilation of LaMEM (2.1.4) should fix this; it does come with the caveat that you need Julia >1.9

**Comment by boriskaus** [comment]
this should be solved in `LaMEM.jl` version 0.4.0 (where MUMPS works again on linux + mac).
